[package]
name = "server"
version = "0.1.0"
authors = ["Matthew Tran <0e4ef622@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-codec = "0.1"
actix-connector = "0.1"
actix-rt = "0.1"
actix-server = "0.1"
actix-service = "0.1"
actix-utils = "0.1"
futures = "0.1"
tokio = "0.1"
